=begin
#Classify

#Classify Custom Image Recognition Service

The version of the OpenAPI document: 1.0.0
Contact: info@inoven.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for create_new_model
  # Create New Model
  # Create a new custom image recognition model
  # @param model_name Set a name for your model
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'create_new_model test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_model
  # Delete Model
  # Delete Model
  # @param model_id You can find your model ids from Classify Dashboard.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'delete_model test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_models_list
  # Get Models List
  # Get the list of of models created 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'get_models_list test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tag_image_by_url
  # Tag Image by Using Image Url
  # Predict image tags by providing image url
  # @param model_id Type your trained model id to predict. You get your model&#39;s id from Classify Dashboard.
  # @param image_url Provide image url to predict
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'tag_image_by_url test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for tag_local_image
  # Predict by Image
  # Send a local image to tag
  # @param model_id Type your trained model id to predict. You get your model&#39;s id from Classify Dashboard.
  # @param [Hash] opts the optional parameters
  # @option opts [File] :file 
  # @return [nil]
  describe 'tag_local_image test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_model
  # Update Model
  # Update Model Name
  # @param model_name Model Name
  # @param model_id Model id to be renamed.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'update_model test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
