=begin
#Classify

#Classify Custom Image Recognition Service

The version of the OpenAPI document: 1.0.0
Contact: info@inoven.ai
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.3.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::InlineObject2
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'InlineObject2' do
  before do
    # run before each test
    @instance = OpenapiClient::InlineObject2.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of InlineObject2' do
    it 'should create an instance of InlineObject2' do
      expect(@instance).to be_instance_of(OpenapiClient::InlineObject2)
    end
  end
  describe 'test attribute "file"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "model_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
